### ISSUE TITLE
bin/magento setup:di:compile is failing after installing the module

### ISSUE THREAD

**Issue by liiskmaa** [boolfly/sales-sequence#1]
Boolfly\SalesSequence\Model\Profile\DataProvider
		Incompatible argument type: Required type: string. Actual type: \Boolfly\SalesSequence\Model\Profile\name

Current lines 48-52
  /**
     * DataProvider constructor.
     * @param $name
     * @param $primaryFieldName
     * @param $requestFieldName

Correct lines 48-52
  /**
     * DataProvider constructor.
     * @param string $name
     * @param string $primaryFieldName
     * @param string $requestFieldName

**Comment by mrkhoa99** [comment]
Thanks @liiskmaa could you please create a PR for this issue?

**Comment by mrkhoa99** [comment]
Thanks @liiskmaa . Merged your PR. Close this issue.
