### ISSUE TITLE
Not compitable with PHP 8.1

### ISSUE THREAD

**Issue by noor-indglobal** [boolfly/sales-sequence#5]
Hi there
Good day

I am checking this extension for sales order prefix. Extension is looks good but it is not compatiable with php 8.1 
can you please check

https://prnt.sc/NtBt5V6zPsC8

Thanks

**Comment by robocrax** [comment]
Not affiliated but here's an alternative just in case: https://fooman.com/magento-extension-invoice-order-number-m2.html
